[package]
org = "ballerina"
name = "xslt"
version = "2.5.0"
authors = ["Ballerina"]
keywords = ["xslt", "xml", "html", "xsl", "transformation"]
repository = "https://github.com/ballerina-platform/module-ballerina-xslt"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.7.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "xslt-native"
version = "2.5.0"
path = "../native/build/libs/xslt-native-2.5.0.jar"

[[platform.java17.dependency]]
path = "./lib/jakarta.activation-1.2.2.jar"
version = "1.2.2"

[[platform.java17.dependency]]
path = "./lib/Saxon-HE-11.4.jar"
version = "11.4"

[[platform.java17.dependency]]
path = "./lib/xmlresolver-4.5.2.jar"
version = "4.5.2"
